// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0LEeujoOr8rhIUTRKueDt74DfYpXHUhU',
    appId: '1:72341903465:web:a9bc9dfc53b1b94bb5aaf8',
    messagingSenderId: '72341903465',
    projectId: 'pet-adaption-app',
    authDomain: 'pet-adaption-app.firebaseapp.com',
    storageBucket: 'pet-adaption-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACtZtEPUF8n_sqhZ1HxXkjhb6N00FiTAU',
    appId: '1:72341903465:android:bb709515f38f5357b5aaf8',
    messagingSenderId: '72341903465',
    projectId: 'pet-adaption-app',
    storageBucket: 'pet-adaption-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBagy2mPOhQATbO4d0PfywSQlNla9VXfH0',
    appId: '1:72341903465:ios:1706674144ca7220b5aaf8',
    messagingSenderId: '72341903465',
    projectId: 'pet-adaption-app',
    storageBucket: 'pet-adaption-app.appspot.com',
    iosClientId:
        '72341903465-9lirs4aglrlomnkfm23vpl57npl3risf.apps.googleusercontent.com',
    iosBundleId: 'com.example.petAdaptionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBagy2mPOhQATbO4d0PfywSQlNla9VXfH0',
    appId: '1:72341903465:ios:9fda7837c8a84cf1b5aaf8',
    messagingSenderId: '72341903465',
    projectId: 'pet-adaption-app',
    storageBucket: 'pet-adaption-app.appspot.com',
    iosClientId:
        '72341903465-kf6fisbpvq4g5rn46eamb214c7m1sla9.apps.googleusercontent.com',
    iosBundleId: 'com.example.petAdaptionApp.RunnerTests',
  );
}
